project:
  type: book
  output-dir: docs

book:
  title: "IMAGEUN Media Group"
  subtitle: "Toolbox for the analysis of international news"
  author: "Claude GRASLAND & Etienne TOUREILLE"
  date: "19/10/2022"
  chapters:
      - index.qmd
      - about.qmd
      - 01-Mediacloud.qmd
      - 02-Quanteda.qmd
      - 03-Dictionary.qmd
      - 04-Tags.qmd
      - 05-HyperCubes.qmd
      - 06-Macroregions.qmd
      - 07-Agenda.qmd
      - 08-Network-Analysis.qmd

knitr:
  opts_chunk: 
    comment: ">" 
    warning: false
    error: false
    message: false





